server:
  port: 9092
spring:
  datasource:
    url: jdbc:h2:file:~/dronesdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
        trace: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: INFO
  file:
    name: "logs/app.log"        
app:
  battery:
    minimum: 25.0    